name: CI

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
   ubuntu:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: cachix/install-nix-action@v16
           with:
              nix_path: nixpkgs=channel:nixos-unstable
         - uses: cachix/cachix-action@v10
           with:
              name: winebox86-apk
              authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
         - run: nix-build
         - uses: actions/upload-artifact@v2
           with:
              name: apks
              path: '*/*.apk'
